version: "3.8"
services:
  web_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
    networks:
      - backend  
  

networks:
  backend:
    driver: bridge
