version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_segura
      MYSQL_DATABASE: express
      MYSQL_USER: mysql
      MYSQL_PASSWORD: senha_mysql
      TZ: America/Sao_Paulo

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/express.sql:/docker-entrypoint-initdb.d/express.sql
    networks:
      - backend

  express_listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt_app
    restart: always
    depends_on:
      - mysql
    networks:
      - backend   
  ### GRAFANA SERVICE ####

  influxdb:
    image: influxdb:1.7
    restart: always
    ports:
     - "8086:8086"
    volumes:
      - grafanadb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: actualdb
  grafana:
   image: grafana/grafana:11.1.9
   restart: always
   ports:
      - "3000:3000"
   depends_on:
      - influxdb
   volumes:
      - grafana:/var/lib/grafana
   environment:
     - GF_SECURITY_ADMIN_PASSWORD=admin  
     - GF_DATASOURCES_MYSQL_ENABLED=true  
     - GF_DATASOURCES_MYSQL_HOST=mysql:3306  
     - GF_DATASOURCES_MYSQL_USER=mysql  
     - GF_DATASOURCES_MYSQL_PASSWORD=senha_mysql  
     - GF_DATASOURCES_MYSQL_DATABASE=iot_data 
   networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: senha_segura
    depends_on:
      - mysql
    networks:
      - backend

  


volumes:
  mysql_data:
  grafana:
  grafanadb:

networks:
  backend:
    driver: bridge
